### ISSUE TITLE
What happened to the Sequel adapter?

### ISSUE THREAD

**Issue by sixtyfive** [digital-fabric/extralite#9]
```ruby
require 'extralight'
require 'sequel'
DB = Sequel.connect 'extralight://db.sqlite3'
table = DB[:some_table]
```
... alas ...
```
Sequel::AdapterNotFound: LoadError: cannot load such file -- sequel/adapters/extralight
```
used to work but now not so anymore, and https://github.com/jeremyevans/sequel/tree/master/lib/sequel/adapters matches that...

**Comment by sixtyfive** [comment]
Whoops, my bad. Bad, bad typo. Sorry!!!

**Comment by ciconia** [comment]
Can you include some code to show what you are doing? I'd like to investigate this.

**Comment by sixtyfive** [comment]
Oh, you mean with regard to the speed thing, @ciconia ?

**Comment by ciconia** [comment]
Sorry for the late reply, yes I'm talking about the speed thing.

**Comment by sixtyfive** [comment]
Hi, no worries, but now it's for me to say sorry as I can't replicate what I thought I had seen a week ago. Here's what I'm doing with that 23GB database file, anyways:

https://gist.github.com/sixtyfive/83ed7504523e5ecb849375fd224168f0
